### ISSUE TITLE
[STEAMDECK] Latest version not applying icon images

### ISSUE THREAD

**Issue by rkr87** [PhilipK/BoilR#121]
Per title, I downloaded the latest FlatPak version of Boilr and ran the import, however after restarting Steam none of my non-Steam games had been updated to use icon images.

Is there something I need to change in settings or are the icons downloaded to a directory somewhere to be manually applied?

**Comment by PhilipK** [comment]
This is most likely related to the newest change that gets icons from steam
grid db.
I will have to see if I can reproduce it later tonight.

**Comment by PhilipK** [comment]
This should be fixed in the latest version v.1.3.2, the flatpak version should be updated soon (i have triggered it but it normally takes an hour or two before it is actually send out by flathub)

**Comment by rkr87** [comment]
Awesome, thanks for sorting so quickly. I did spot that the current version of BoilR I'm using is actually downloading the icons to the config/grid/ folder just not applying them in Steam.

**Comment by PhilipK** [comment]
Yes, it was downloading them. It was setting them too.... But the
downloaded files could be jpg,png or ico files.
It assumed they where always ico.
That meant that steam would read them as ico, go "hmm I can't read that
file" and then it would unset them.
Now it download with the correct file extension.

**Comment by rkr87** [comment]
Hi,

I've just tried running the updated version and I still have the same issue, they re being downloaded as .ico files but being set as the icon within Steam.

**Comment by PhilipK** [comment]
In the newest version the icons should be named appid-icon.png or appid-icon.icon. Are you seeing that?

**Comment by rkr87** [comment]
Yes, that's what I'm seeing screenshots below.
![Screenshot_20220514_183535](https://user-images.githubusercontent.com/43894515/168443037-0a244c26-c2ce-48fe-991c-dd8af6057cea.png)
![Screenshot_20220514_183628](https://user-images.githubusercontent.com/43894515/168443038-c09fc387-e877-41a2-a877-578909fbb478.png)

**Comment by PhilipK** [comment]
I will have to see if I can reproduce this then.

**Comment by PhilipK** [comment]
which platform are you importing from?

**Comment by PhilipK** [comment]
I was just able to reproduce this on linux. Will look into why this is happening.

**Comment by rkr87** [comment]
I'm importing from Heroic and also have some manually created shortcuts that BoilR also pulls images for.

**Comment by PhilipK** [comment]
If you simply run the import twice, does that help?

**Comment by rkr87** [comment]
Unfortunately not, I tried running it 3 times to be sure, both with steam open and with steam closed. Still no logos attached.

**Comment by PhilipK** [comment]
Alright, version 1.3.4 should solve this problem.
I was able to recreate it for one of my games and it got fixed in 1.3.4.
Again, if it is not fixed for you please let me know.

Remember, it can take a while for flathub to update after I have pushed an update.

**Comment by rkr87** [comment]
Hi

I've tried the latest version and unfortunately there's no change, none of my shortcuts have been updated with icons.

In the hopes of helping figure this out, I manually assigned some icons to some of my non Steam games and went digging through my config files to see whether there was any further required and it looks like the shortcuts.vdf file in user config needs to be updated with and icon keyvalue, screenshot below.
![Screenshot_20220515_092820](https://user-images.githubusercontent.com/43894515/168464178-037dbb9b-43c9-4dae-bd8a-59eceef47681.png)
Hope that helps.

**Comment by PhilipK** [comment]
Oh, wait. I think I know what might be wrong.
Could you try to delete all the old images? Either delete all images and
import again or just delete the wrong files and then import?

**Comment by rkr87** [comment]
Still no luck. I deleted everything in my grid folder and did a full import and all icons for custom games are still missing.

**Comment by PhilipK** [comment]
I am stomped, don't know what it can be then.
Steam deck calculator says one week till I get my steam deck, hopefully it
will help with fixing the random bugs that only seem to happen on Steam
Deck.

Alternatively, can you upload your shortcuts file and I can see if I can
reproduce it on my machine.

**Comment by rkr87** [comment]
Shortcuts file attached, I changed the extension to .zip to bypass Github's restrictions, it'll need changing back to .vdf.

[shortcuts.zip](https://github.com/PhilipK/BoilR/files/8698203/shortcuts.zip)

**Comment by rkr87** [comment]
i don't know if this will help at all but I recently installed Steam Rom Manager and that app **is** able to update my icons in Steam, I'm not sure what that dev's implementation is doing different to yours but might be worth a look as I believe it's FOSS.
